### ISSUE TITLE
import Airtm from "airtm";

### ISSUE THREAD

**Issue by ProgrammerSany** [dinels12/airtm-node#1]
From where do I need to import  Airtm??

If I import it from import Airtm from "airtm"; it's throwing error, 
`airtm.getPartnerInformation()` is not a function.

**Comment by dinels12** [comment]
Hi, thanks you for reporting this issue, i already updated the github Readme documentation
you need to use the @dinels/airtm npm package.

import Airtm from "@dinels/airtm";

i hope this can be helpful for you.
